{{- $fullName := include "prom2click.fullname" . -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prom2click.fullname" . }}-clickhouse
  namespace: {{ .Release.Namespace }}
data:
  CLICKHOUSE_HOST: "{{ $fullName }}-clickhouse"
  CLICKHOUSE_PORT: "80"
  CLICKHOUSE_DATABASE: "{{ .Values.clickhouse.database }}"
  CLICKHOUSE_READ_TIMEOUT: "{{ .Values.clickhouse.readTimeout }}"
  CLICKHOUSE_WRITE_TIMEOUT: "{{ .Values.clickhouse.writeTimeout }}"
