#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: {{ include "prom2click.fullname" . }}-clickhouse
#  labels:
#    {{- include "prom2click.labels" . | nindent 4 }}
#subsets:
#  - addresses:
#      - ip: {{ .Values.clickhouse.host }}
#    ports:
#      - port: {{ .Values.clickhouse.port }}
