---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registryCredentials | b64enc | quote }}
