---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prom2click.fullname" . }}-clickhouse-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.clickhouse.username | b64enc | quote }}
  password: {{ .Values.clickhouse.password | b64enc | quote }}

{{ if .Values.registryCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registryCredentials | b64enc | quote }}
{{ end }}
