---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prom2click.fullname" . }}-clickhouse-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.clickhouse.username | b64enc | quote }}
  password: {{ .Values.clickhouse.password | b64enc | quote }}
