apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prom2click.fullname" . }}
  labels:
    {{- include "prom2click.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "prom2click.fullname" . }}
  updateStrategy:
      type: {{ .Values.updateStrategy.type }}
      {{- if (eq "Recreate" .Values.updateStrategy.type) }}
      rollingUpdate: null
      {{- end }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "prom2click.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "prom2click.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prom2click.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "prom2click.fullname" . }}-clickhouse
          env:
            - name: "CLICKHOUSE_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "prom2click.fullname" . }}-clickhouse-secret
                  key: username
            - name: "CLICKHOUSE_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "prom2click.fullname" . }}-clickhouse-secret
                  key: password
          ports:
            - name: http
              containerPort: 9201
              protocol: TCP
          command:
            - 'prom2click'
            - '-ch.dsn="\'
            - 'tcp://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}?\'
            - 'username=${CLICKHOUSE_USER}&\'
            - 'password=${CLICKHOUSE_USER_PASSWORD}&\'
            - 'database=${CLICKHOUSE_DATABASE}&\'
            - 'read_timeout=${CLICKHOUSE_READ_TIMEOUT}&\'
            - 'write_timeout=${CLICKHOUSE_WRITE_TIMEOUT}"'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
